## IV Style Wanted Level System - San Andreas

[SETTINGS]

##    BASE      #########################################################################

#Search radius for 1 star wanted level
#Higher wanted levels will use a multiple of this one (2x for 2*, 3x for 3* and so on)

BaseRadius=200.0 #(default 200.0)

#Duration of being spotted in miliseconds. By default it's 50000
#This means that once you are spotted by a cop, your location will be alerted for this long
TimeSeen=5000  #(5000)


#From here every value should be floats
		
##    RANGES      ########################################################################

#The base range from a cop so he can report your location. This is the case of ground cops during daytime.

BaseRange=30.0  #(30.0)

AirUnitRange=250.0 #(250.0)

WaterUnitMultp=10.0 #(10.0)

FogRange=20.0 #(20.0)

NightMultp=0.85 #(0.85)

MaxScanRange=450.0 #(450.0)



##    SPEEDS      #########################################################################S
Star3SearchSpeed=34.0

Star3PursuitSpeed=54.0
Star4SearchSpeed=34.0
Star4PursuitSpeed=72.0
Star5SearchSpeed=43.0
Star5PursuitSpeed=75.0
Star6SearchSpeed=43.0
Star6PursuitSpeed=78.0

