## IV Style Wanted Level System - San Andreas

[SETTINGS]

##    BASE      #########################################################################

# Search radius for 1 star wanted level
# Higher wanted levels will use a multiple of this one (2x for 2*, 3x for 3* and so on)

BaseRadius=200.0 #(default 200.0)

# Duration of being spotted in miliseconds. By default it's 5000.
# Unlike other values on this file, this should be an integer
# This means that once you are spotted by a cop, your location will be alerted for this long
TimeSeen=5000  #(5000)
		
##    RANGES      #######################################################################

# Range is how close you are to a cop so he can detect and confirm your location. This is the case of ground cops during daytime.
BaseRange=30.0  #(30.0)

# Range of the air support units. This one is always the same in all conditions and should be much further away.
# However, it should not exceed the maximum scan range below
AirUnitRange=250.0 #(250.0)

# Water units use a multiplier for spot distance. They too can see further away.
# By default, it's 300.0 or 10 times the base range. This should not exceed the maximum scan range.
WaterUnitMultp=10.0 #(10.0)

# When the weather reduces vision, this range will be used instead of the base range above.
FogRange=20.0 #(20.0)

# At night, this value will be multiplied to the base range.
NightMultp=0.85 #(0.85)

# How far away should the script scan for police.
# It will first scan all the cops in this range, and then check if they can spot you using the above ranges
MaxScanRange=450.0 #(450.0)



##    SPEEDS      #########################################################################
# For each of your wanted level from 3 stars, you can tweak the speed of the police cars
# Each level has a pair of speed, the search speed will be slower and is used when cops are not spotting you
# If they spot you, they should pursue at a higher speed

Star3SearchSpeed=34.0
Star3PursuitSpeed=54.0

Star4SearchSpeed=34.0
Star4PursuitSpeed=72.0

Star5SearchSpeed=43.0
Star5PursuitSpeed=75.0

Star6SearchSpeed=43.0
Star6PursuitSpeed=78.0

